version: 1.0.{build}
branches:
  only:
  - master
skip_tags: true

build: false

environment:
  matrix:
    - PYTHON_VERSION: 2.7
      MINICONDA: C:\Miniconda

init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"

install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - "conda create -q -n test-environment python=%PYTHON_VERSION% numpy scipy nose"
  - activate test-environment
  - pip install coverage

test_script:
  - cmd: echo This is a test!
  - nosetests

on_success:
- cmd: echo Build successfully!
on_failure:
- cmd: echo Build Failed!
