version: 1.0.{build}
branches:
  only:
  - master
skip_tags: true

build_script:
- cmd: echo Hello World!

test_script:
- cmd: echo This is a test!

on_success:
- cmd: echo Build successfully!
on_failure:
- cmd: echo Build Failed!
