version: 1.0.{build}
branches:
  only:
  - master
skip_tags: true

build script:
- cmd: echo Hello World!

test script:
- cmd: echo This is a test!

on success:
- cmd: echo Build successfully!
on failure:
- cmd: echo Build Failed!
